### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by Nazat95** [Coffee2CodeNL/gebaar-libinput#1]
Hello, 

I am getting this error when trying to install this on my laptop running Kubuntu 18.10. Sorry I am kinda new to Linux.

Thanks
![libinput](https://user-images.githubusercontent.com/25968402/52888941-cc375f80-314b-11e9-8496-44814315e317.png)

**Comment by Coffee2CodeNL** [comment]
Try this:

`sudo apt install libinput-dev libsystemd-dev`

**Comment by Nazat95** [comment]
Thank you installing that fixed it.
